
BASIC_FILE_NAME = 'basic.html'
DOCTYPE = '<!DOCTYPE html>'
CSS_MARKER = '<!--link_css-->'
CSS_BEGIN_TAG = '<link rel="stylesheet" href="'
CSS_END_TAG = '">'
NEW_LINE = '\n'
# BODY_MAIN_CONTENTS_MARKER = '<!--main contents-->'
# BODY_MAIN_CONTENTS_MARKER = '<body><!--main contents--></body>'
BODY_MAIN_CONTENTS_MARKER = '    <body><!--main contents--></body>'

class HtmlTagName():
    P = 'p'
    DIV = 'div'
    SPAN = 'span'
    H1 = 'h1'
    H2 = 'h2'
    H3 = 'h3'
    BODY = 'body'
    HTML = 'html'
    IMG = 'img'